// <auto-generated />
using AccesoDatos.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccesoDatos.Migrations
{
    [DbContext(typeof(ProyectoContext))]
    partial class ProyectoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccesoDatos.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("dni");

                    b.Property<int>("Edad")
                        .HasColumnType("int")
                        .HasColumnName("edad");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PK__alumno__3213E83F9FD3A854");

                    b.ToTable("alumno", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Models.Asignatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Creditos")
                        .HasColumnType("int")
                        .HasColumnName("creditos");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("Profesor")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("profesor");

                    b.HasKey("Id")
                        .HasName("PK__asignatu__3213E83FADF8F1B2");

                    b.HasIndex("Profesor");

                    b.ToTable("asignatura", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Models.Calificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<int>("MatriculaId")
                        .HasColumnType("int")
                        .HasColumnName("matriculaId");

                    b.Property<float>("Nota")
                        .HasColumnType("real")
                        .HasColumnName("nota");

                    b.Property<int>("Porcentaje")
                        .HasColumnType("int")
                        .HasColumnName("porcentaje");

                    b.HasKey("Id")
                        .HasName("PK__califica__3213E83FEF89952F");

                    b.HasIndex("MatriculaId");

                    b.ToTable("calificacion", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Models.Matricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int")
                        .HasColumnName("alumnoId");

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("int")
                        .HasColumnName("asignaturaId");

                    b.HasKey("Id")
                        .HasName("PK__matricul__3213E83FE599E2B7");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("AsignaturaId");

                    b.ToTable("matricula", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Models.Profesor", b =>
                {
                    b.Property<string>("Usuario")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("usuario");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pass");

                    b.HasKey("Usuario")
                        .HasName("PK__profesor__9AFF8FC7730DD581");

                    b.ToTable("profesor", (string)null);
                });

            modelBuilder.Entity("AccesoDatos.Models.Asignatura", b =>
                {
                    b.HasOne("AccesoDatos.Models.Profesor", "ProfesorNavigation")
                        .WithMany("Asignaturas")
                        .HasForeignKey("Profesor")
                        .HasConstraintName("FK__asignatur__profe__29572725");

                    b.Navigation("ProfesorNavigation");
                });

            modelBuilder.Entity("AccesoDatos.Models.Calificacion", b =>
                {
                    b.HasOne("AccesoDatos.Models.Matricula", "Matricula")
                        .WithMany("Calificacions")
                        .HasForeignKey("MatriculaId")
                        .IsRequired()
                        .HasConstraintName("FK__calificac__matri__300424B4");

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("AccesoDatos.Models.Matricula", b =>
                {
                    b.HasOne("AccesoDatos.Models.Alumno", "Alumno")
                        .WithMany("Matriculas")
                        .HasForeignKey("AlumnoId")
                        .IsRequired()
                        .HasConstraintName("FK__matricula__alumn__2C3393D0");

                    b.HasOne("AccesoDatos.Models.Asignatura", "Asignatura")
                        .WithMany("Matriculas")
                        .HasForeignKey("AsignaturaId")
                        .IsRequired()
                        .HasConstraintName("FK__matricula__asign__2D27B809");

                    b.Navigation("Alumno");

                    b.Navigation("Asignatura");
                });

            modelBuilder.Entity("AccesoDatos.Models.Alumno", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("AccesoDatos.Models.Asignatura", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("AccesoDatos.Models.Matricula", b =>
                {
                    b.Navigation("Calificacions");
                });

            modelBuilder.Entity("AccesoDatos.Models.Profesor", b =>
                {
                    b.Navigation("Asignaturas");
                });
#pragma warning restore 612, 618
        }
    }
}
